{% set name = "ctd" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctd-{{ version }}.tar.gz
  sha256: 19d2f29300added26d947740a609874588dccd57e0e48c459743bf11923ab764

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools >=41.2
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - chardet
    - gsw >=3.3.0
    - matplotlib-base
    - numpy
    - pandas >=0.24.0
    - pandas-flavor >=0.1.2
    - scipy

test:
  imports:
    - ctd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/python-ctd
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Tools to load hydrographic data formats as pandas DataFrames

extra:
  recipe-maintainers:
    - ocefpaf
