{% set version = "1.1.1" %}

package:
  name: ctd
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/ctd/ctd-{{ version }}.tar.gz
  sha256: 0605bbbd182c8e3aaba8487559c8a1f0fc125738e38943678aaf3448326df011

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - gsw >=3.3.0
    - matplotlib-base
    - numpy
    - pandas-flavor
    - pandas >=0.24.0
    - scipy


test:
  imports:
    - ctd

about:
  home: https://github.com/pyoceans/python-ctd
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Tools to load hydrographic data formats as pandas DataFrames

extra:
  recipe-maintainers:
    - ocefpaf
