{% set version = "0.3.0" %}

package:
  name: ctd
  version: {{ version }}

source:
  fn: ctd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/ctd/ctd-{{ version }}.tar.gz
  sha256: c5144bf2200cd366fabacdd3c4dbe6cfd234a57beaf1aa221b159f5462bc4677

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - gsw

test:
  imports:
    - ctd

about:
  home: https://github.com/pyoceans/python-ctd
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Tools to load hydrographic data formats as pandas DataFrames.'

extra:
  recipe-maintainers:
    - ocefpaf
