{% set name = "ctd" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctd-{{ version }}.tar.gz
  sha256: 54d672ff0c1a6c1d7e7ecf2fc56d4763b23723c5a60db44715dccc76d5a8f470

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - gsw >=3.3.0
    - matplotlib-base
    - numpy
    - pandas-flavor >=0.1.2
    - pandas >=0.24.0
    - scipy
    - chardet

test:
  imports:
    - ctd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/python-ctd
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Tools to load hydrographic data formats as pandas DataFrames

extra:
  recipe-maintainers:
    - ocefpaf
