travis:
  secure:
    BINSTAR_TOKEN: RP9+LjKSbEbd/AAODhnWZEw/JWNtkxpvOHyBMB/g7tcYMvlYdO7DherafP4azp3aRI34ZcsT9S8dreDF2yt5w25b2XApLykU9hiPmc/tXfN8lTx1FXbik/ZuSh1z2MepypHGKT8WmPGsK1t37qAGQ/KFdtmeENkepn/2Amy0m1TWkmbYGncewH0JNFZucveSxPPvoubO/rg4yRaChsI3mVb1AjHG4s6slH1uJlt4/qZtb5qGqexALQwdjUfFaHevkoGCKb4GZ9qBDtwHgRZcwqifsferS8QDtU1S+HqubBPLCWU0wqjqv1z32kkucE5CKaTHmCc4gKjDwKrQIWWsk3LwJpmSQwyE6BMpHYkovEGpeVv0mZ3iNyIDZ9+AP+3npd+HZ0NUiECGrbkurTJ2aN6x+z7rzR6rYFf8OqTbCTojtn4AtaiI8YyUpfvuqN2ZKKj1/Xod7mIbzJhh0Z+AviuWyA1DbsA3bRsm3bc4HEjRjXpdQnKkH5jlQWoW453sZn5n0MfdUIXLkwcA+IqR2ZPOh+AxCYmw0K7Thy7+9y1d60J0T1ZMflYVxPD7cWqjSbSD6RuRnIGgB7C2BHPaNAPIQm+ncXS6jBZ0ySG9iTQnRbjReUy3K8TviyCjQKbwfDuZbk/x/WXAVjflT4GdpzJfUOq6aBAINegWSgLUJBE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
