travis:
  secure:
    BINSTAR_TOKEN: qBtWNPJGxYF/MaoAtNvzbm2My2nAfhtzn+8oTiLmTziPWsqPtz22CbRW5TwpXdAkUbm5BmZrW8iGcf8OiIGG7tR3+OG+E5zsV2Oe+pBW6aHP7RKoFYFLTgnlZ/nyUxslFJnNThoJNwORKj1ACVKeW2HQF41PS+wvptGfl2cLuSC5BfSPyLIZ3pbZsE40OBDh+lwllpDuKBl2qZVyIVFFQDeet4SQwkFVJHwEsQo+8UYjzPaZYsmncI2U/HdTz2ver90MKv3Xdlz7dyueJKysJLp4KCriwe7BxJxXoQzqwFE8Mv3du8qQMeQ4cnTvD+6oT3DlFlOTw+4W3Hx6aCVywsusOoUwoiQBfy3p1XWh5+OOgL5o/1gpuHdJfSaTkkqdB/U7PKIUySO6UNLaNwQjtiXV1XOVj9Xkhumxb8/mtzBdmRxAAnUff6Rx6hUF6HjZd5uGlfTTQW7Ot0fMlJ6N3gkJxMb4d59SOkqK3GqL5M4CyFt34R6ePT8IUHodG/24wIG092c534/yshksUfDlRvsuJ/2ZDqWPMuUL47H0ez4gTbtcOHTYlA1b6otCBHf5/qWbD5rBvlCOHOolPPo0SPzOgOo258mbgOs9GF8XThEh0aUwFvv9KYN4ApBFgxacuQy26rHr7Tu0QA7mh30Ko6MqUjyjdNLOCGWww9UVN6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
